# Generated by Django 3.1.7 on 2021-04-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'clothes'), (2, 'accessories')], default=1, verbose_name='Вид продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Категория'),
        ),
    ]
