# Generated by Django 3.1.7 on 2021-04-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
